from __future__ import annotations

from typing import Dict, List


def _entry(
    display_name: str,
    enable_flag_name: str,
    value_var: str,
    history_var: str,
    cash_var: str,
    positions_var: str,
) -> Dict[str, str]:
    return {
        "display_name": display_name,
        "enable_flag_name": enable_flag_name,
        "value_var": value_var,
        "history_var": history_var,
        "cash_var": cash_var,
        "positions_var": positions_var,
    }


STRATEGY_REGISTRY: Dict[str, Dict[str, str]] = {
    "static_bh_1y": _entry("Static BH 1Y", "ENABLE_STATIC_BH", "static_bh_1y_portfolio_value", "static_bh_1y_portfolio_history", "static_bh_1y_cash", "current_static_bh_1y_stocks"),
    "static_bh_6m": _entry("Static BH 6M", "ENABLE_STATIC_BH", "static_bh_6m_portfolio_value", "static_bh_6m_portfolio_history", "static_bh_6m_cash", "current_static_bh_6m_stocks"),
    "static_bh_3m": _entry("Static BH 3M", "ENABLE_STATIC_BH", "static_bh_3m_portfolio_value", "static_bh_3m_portfolio_history", "static_bh_3m_cash", "current_static_bh_3m_stocks"),
    "static_bh_1m": _entry("Static BH 1M", "ENABLE_STATIC_BH", "static_bh_1m_portfolio_value", "static_bh_1m_portfolio_history", "static_bh_1m_cash", "current_static_bh_1m_stocks"),
    "dynamic_bh_1y": _entry("Dynamic BH 1Y", "ENABLE_DYNAMIC_BH_1Y", "dynamic_bh_portfolio_value", "dynamic_bh_portfolio_history", "dynamic_bh_cash", "current_dynamic_bh_stocks"),
    "dynamic_bh_6m": _entry("Dynamic BH 6M", "ENABLE_DYNAMIC_BH_6M", "dynamic_bh_6m_portfolio_value", "dynamic_bh_6m_portfolio_history", "dynamic_bh_6m_cash", "current_dynamic_bh_6m_stocks"),
    "dynamic_bh_3m": _entry("Dynamic BH 3M", "ENABLE_DYNAMIC_BH_3M", "dynamic_bh_3m_portfolio_value", "dynamic_bh_3m_portfolio_history", "dynamic_bh_3m_cash", "current_dynamic_bh_3m_stocks"),
    "dynamic_bh_1m": _entry("Dynamic BH 1M", "ENABLE_DYNAMIC_BH_1M", "dynamic_bh_1m_portfolio_value", "dynamic_bh_1m_portfolio_history", "dynamic_bh_1m_cash", "current_dynamic_bh_1m_stocks"),
    "dynamic_bh_1y_vol_filter": _entry("Dynamic BH 1Y+Vol", "ENABLE_DYNAMIC_BH_1Y_VOL_FILTER", "dynamic_bh_1y_vol_filter_portfolio_value", "dynamic_bh_1y_vol_filter_portfolio_history", "dynamic_bh_1y_vol_filter_cash", "current_dynamic_bh_1y_vol_filter_stocks"),
    "dynamic_bh_1y_trailing_stop": _entry("Dynamic BH 1Y+TS", "ENABLE_DYNAMIC_BH_1Y_TRAILING_STOP", "dynamic_bh_1y_trailing_stop_portfolio_value", "dynamic_bh_1y_trailing_stop_portfolio_history", "dynamic_bh_1y_trailing_stop_cash", "current_dynamic_bh_1y_trailing_stop_stocks"),
    "risk_adj_mom": _entry("Risk-Adj Mom", "ENABLE_RISK_ADJ_MOM", "risk_adj_mom_portfolio_value", "risk_adj_mom_portfolio_history", "risk_adj_mom_cash", "current_risk_adj_mom_stocks"),
    "mean_reversion": _entry("Mean Reversion", "ENABLE_MEAN_REVERSION", "mean_reversion_portfolio_value", "mean_reversion_portfolio_history", "mean_reversion_cash", "current_mean_reversion_stocks"),
    "quality_momentum": _entry("Quality+Mom", "ENABLE_QUALITY_MOM", "quality_momentum_portfolio_value", "quality_momentum_portfolio_history", "quality_momentum_cash", "current_quality_momentum_stocks"),
    "momentum_ai_hybrid": _entry("Momentum+AI", "ENABLE_MOMENTUM_AI_HYBRID", "momentum_ai_hybrid_portfolio_value", "momentum_ai_hybrid_portfolio_history", "momentum_ai_hybrid_cash", "momentum_ai_hybrid_positions"),
    "volatility_adj_mom": _entry("Vol-Adj Mom", "ENABLE_VOLATILITY_ADJ_MOM", "volatility_adj_mom_portfolio_value", "volatility_adj_mom_portfolio_history", "volatility_adj_mom_cash", "current_volatility_adj_mom_stocks"),
    "sector_rotation": _entry("Sector Rotation", "ENABLE_SECTOR_ROTATION", "sector_rotation_portfolio_value", "sector_rotation_portfolio_history", "sector_rotation_cash", "current_sector_rotation_etfs"),
    "ratio_3m_1y": _entry("3M/1Y Ratio", "ENABLE_3M_1Y_RATIO", "ratio_3m_1y_portfolio_value", "ratio_3m_1y_portfolio_history", "ratio_3m_1y_cash", "ratio_3m_1y_positions"),
    "ratio_1y_3m": _entry("1Y/3M Ratio", "ENABLE_3M_1Y_RATIO", "ratio_1y_3m_portfolio_value", "ratio_1y_3m_portfolio_history", "ratio_1y_3m_cash", "ratio_1y_3m_positions"),
    "ratio_1m_3m": _entry("1M/3M Ratio", "ENABLE_1M_3M_RATIO", "ratio_1m_3m_portfolio_value", "ratio_1m_3m_portfolio_history", "ratio_1m_3m_cash", "ratio_1m_3m_positions"),
    "momentum_volatility_hybrid": _entry("Mom-Vol Hybrid", "ENABLE_MOMENTUM_VOLATILITY_HYBRID", "momentum_volatility_hybrid_portfolio_value", "momentum_volatility_hybrid_portfolio_history", "momentum_volatility_hybrid_cash", "momentum_volatility_hybrid_positions"),
    "momentum_volatility_hybrid_6m": _entry("Mom-Vol Hybrid 6M", "ENABLE_MOMENTUM_VOLATILITY_HYBRID_6M", "momentum_volatility_hybrid_6m_portfolio_value", "momentum_volatility_hybrid_6m_portfolio_history", "momentum_volatility_hybrid_6m_cash", "momentum_volatility_hybrid_6m_positions"),
    "momentum_volatility_hybrid_1y": _entry("Mom-Vol Hybrid 1Y", "ENABLE_MOMENTUM_VOLATILITY_HYBRID_1Y", "momentum_volatility_hybrid_1y_portfolio_value", "momentum_volatility_hybrid_1y_portfolio_history", "momentum_volatility_hybrid_1y_cash", "momentum_volatility_hybrid_1y_positions"),
    "momentum_volatility_hybrid_1y3m": _entry("Mom-Vol Hybrid 1Y/3M", "ENABLE_MOMENTUM_VOLATILITY_HYBRID_1Y3M", "momentum_volatility_hybrid_1y3m_portfolio_value", "momentum_volatility_hybrid_1y3m_portfolio_history", "momentum_volatility_hybrid_1y3m_cash", "momentum_volatility_hybrid_1y3m_positions"),
    "price_acceleration": _entry("Price Acceleration", "ENABLE_PRICE_ACCELERATION", "price_acceleration_portfolio_value", "price_acceleration_portfolio_history", "price_acceleration_cash", "current_price_acceleration_stocks"),
    "price_curvature": _entry("Price Curvature", "ENABLE_PRICE_CURVATURE", "price_curvature_portfolio_value", "price_curvature_portfolio_history", "price_curvature_cash", "current_price_curvature_stocks"),
    "confirmed_leaders": _entry("Confirmed Leaders", "ENABLE_CONFIRMED_LEADERS", "confirmed_leaders_portfolio_value", "confirmed_leaders_portfolio_history", "confirmed_leaders_cash", "current_confirmed_leaders_stocks"),
    "foresight_mimic": _entry("Foresight Mimic Accel", "ENABLE_FORESIGHT_MIMIC", "foresight_mimic_portfolio_value", "foresight_mimic_portfolio_history", "foresight_mimic_cash", "current_foresight_mimic_stocks"),
    "defensive_momentum": _entry("Defensive Momentum", "ENABLE_DEFENSIVE_MOMENTUM", "defensive_momentum_portfolio_value", "defensive_momentum_portfolio_history", "defensive_momentum_cash", "current_defensive_momentum_stocks"),
    "turnaround": _entry("Turnaround", "ENABLE_TURNAROUND", "turnaround_portfolio_value", "turnaround_portfolio_history", "turnaround_cash", "current_turnaround_stocks"),
    "deep_recovery": _entry("Deep Recovery", "ENABLE_DEEP_RECOVERY", "deep_recovery_portfolio_value", "deep_recovery_portfolio_history", "deep_recovery_cash", "current_deep_recovery_stocks"),
    "adaptive_ensemble": _entry("Adaptive Ensemble", "ENABLE_ADAPTIVE_STRATEGY", "adaptive_ensemble_portfolio_value", "adaptive_ensemble_portfolio_history", "adaptive_ensemble_cash", "adaptive_ensemble_positions"),
    "enhanced_volatility": _entry("Enhanced Volatility", "ENABLE_ENHANCED_VOLATILITY", "enhanced_volatility_portfolio_value", "enhanced_volatility_portfolio_history", "enhanced_volatility_cash", "enhanced_volatility_positions"),
    "ai_volatility_ensemble": _entry("AI Volatility Ensemble", "ENABLE_AI_VOLATILITY_ENSEMBLE", "ai_volatility_ensemble_portfolio_value", "ai_volatility_ensemble_portfolio_history", "ai_volatility_ensemble_cash", "ai_volatility_ensemble_positions"),
    "multi_tf_ensemble": _entry("Multi-Horizon Ensemble", "ENABLE_MULTI_TIMEFRAME_ENSEMBLE", "multi_tf_ensemble_portfolio_value", "multi_tf_ensemble_portfolio_history", "multi_tf_ensemble_cash", "multi_tf_ensemble_positions"),
    "multi_tf_intraday_ensemble": _entry("Multi-Horizon Intraday", "ENABLE_MULTI_TIMEFRAME_INTRADAY_ENSEMBLE", "multi_tf_intraday_ensemble_portfolio_value", "multi_tf_intraday_ensemble_portfolio_history", "multi_tf_intraday_ensemble_cash", "multi_tf_intraday_ensemble_positions"),
    "correlation_ensemble": _entry("Correlation Ensemble", "ENABLE_CORRELATION_ENSEMBLE", "correlation_ensemble_portfolio_value", "correlation_ensemble_portfolio_history", "correlation_ensemble_cash", "correlation_ensemble_positions"),
    "risk_adj_mom_sentiment": _entry("RiskAdj Sent", "ENABLE_RISK_ADJ_MOM_SENTIMENT", "risk_adj_mom_sentiment_portfolio_value", "risk_adj_mom_sentiment_portfolio_history", "risk_adj_mom_sentiment_cash", "risk_adj_mom_sentiment_positions"),
    "voting_ensemble": _entry("Voting Ensemble", "ENABLE_VOTING_ENSEMBLE", "voting_ensemble_portfolio_value", "voting_ensemble_portfolio_history", "voting_ensemble_cash", "voting_ensemble_positions"),
    "mom_accel": _entry("Mom Acceleration", "ENABLE_MOMENTUM_ACCELERATION", "mom_accel_portfolio_value", "mom_accel_portfolio_history", "mom_accel_cash", "mom_accel_positions"),
    "concentrated_3m": _entry("Concentrated 3M", "ENABLE_CONCENTRATED_3M", "concentrated_3m_portfolio_value", "concentrated_3m_portfolio_history", "concentrated_3m_cash", "concentrated_3m_positions"),
    "dual_momentum": _entry("Dual Momentum", "ENABLE_DUAL_MOMENTUM", "dual_mom_portfolio_value", "dual_mom_portfolio_history", "dual_mom_cash", "dual_mom_positions"),
    "trend_atr": _entry("Trend ATR", "ENABLE_TREND_FOLLOWING_ATR", "trend_atr_portfolio_value", "trend_atr_portfolio_history", "trend_atr_cash", "trend_atr_positions"),
    "elite_hybrid": _entry("Elite Hybrid", "ENABLE_ELITE_HYBRID", "elite_hybrid_portfolio_value", "elite_hybrid_portfolio_history", "elite_hybrid_cash", "elite_hybrid_positions"),
    "elite_risk": _entry("Elite Risk", "ENABLE_ELITE_RISK", "elite_risk_portfolio_value", "elite_risk_portfolio_history", "elite_risk_cash", "elite_risk_positions"),
    "risk_adj_mom_6m": _entry("Risk-Adj Mom 6M", "ENABLE_RISK_ADJ_MOM_6M", "risk_adj_mom_6m_portfolio_value", "risk_adj_mom_6m_portfolio_history", "risk_adj_mom_6m_cash", "current_risk_adj_mom_6m_stocks"),
    "risk_adj_mom_6m_monthly": _entry("RiskAdj 6M Mth", "ENABLE_RISK_ADJ_MOM_6M_MONTHLY", "risk_adj_mom_6m_monthly_portfolio_value", "risk_adj_mom_6m_monthly_portfolio_history", "risk_adj_mom_6m_monthly_cash", "risk_adj_mom_6m_monthly_positions"),
    "risk_adj_mom_3m": _entry("Risk-Adj Mom 3M", "ENABLE_RISK_ADJ_MOM_3M", "risk_adj_mom_3m_portfolio_value", "risk_adj_mom_3m_portfolio_history", "risk_adj_mom_3m_cash", "current_risk_adj_mom_3m_stocks"),
    "risk_adj_mom_3m_monthly": _entry("RiskAdj 3M Mth", "ENABLE_RISK_ADJ_MOM_3M_MONTHLY", "risk_adj_mom_3m_monthly_portfolio_value", "risk_adj_mom_3m_monthly_portfolio_history", "risk_adj_mom_3m_monthly_cash", "risk_adj_mom_3m_monthly_positions"),
    "risk_adj_mom_3m_sentiment": _entry("RiskAdj 3M Sent", "ENABLE_RISK_ADJ_MOM_3M_SENTIMENT", "risk_adj_mom_3m_sentiment_portfolio_value", "risk_adj_mom_3m_sentiment_portfolio_history", "risk_adj_mom_3m_sentiment_cash", "risk_adj_mom_3m_sentiment_positions"),
    "risk_adj_mom_3m_market_up": _entry("RiskAdj 3M Up", "ENABLE_RISK_ADJ_MOM_3M_MARKET_UP", "risk_adj_mom_3m_market_up_portfolio_value", "risk_adj_mom_3m_market_up_portfolio_history", "risk_adj_mom_3m_market_up_cash", "risk_adj_mom_3m_market_up_positions"),
    "risk_adj_mom_3m_with_stops": _entry("RiskAdj 3M Stop", "ENABLE_RISK_ADJ_MOM_3M_WITH_STOPS", "risk_adj_mom_3m_with_stops_portfolio_value", "risk_adj_mom_3m_with_stops_portfolio_history", "risk_adj_mom_3m_with_stops_cash", "risk_adj_mom_3m_with_stops_positions"),
    "vol_sweet_mom": _entry("VolSweet Mom", "ENABLE_VOL_SWEET_MOM", "vol_sweet_mom_portfolio_value", "vol_sweet_mom_portfolio_history", "vol_sweet_mom_cash", "vol_sweet_mom_positions"),
    "risk_adj_mom_1m_vol_sweet": _entry("1M VolSweet", "ENABLE_RISK_ADJ_MOM_1M_VOL_SWEET", "risk_adj_mom_1m_vol_sweet_portfolio_value", "risk_adj_mom_1m_vol_sweet_portfolio_history", "risk_adj_mom_1m_vol_sweet_cash", "current_risk_adj_mom_1m_vol_sweet_stocks"),
    "bh_1y_volsweet_accel": _entry("BH 1Y VolSweet Accel", "ENABLE_BH_1Y_VOL_SWEET_ACCEL", "bh_1y_volsweet_accel_portfolio_value", "bh_1y_volsweet_accel_portfolio_history", "bh_1y_volsweet_accel_cash", "current_bh_1y_volsweet_accel_stocks"),
    "bh_1y_dynamic_accel": _entry("BH 1Y Dynamic Accel", "ENABLE_BH_1Y_DYNAMIC_ACCEL", "bh_1y_dynamic_accel_portfolio_value", "bh_1y_dynamic_accel_portfolio_history", "bh_1y_dynamic_accel_cash", "bh_1y_dynamic_accel_positions"),
    "risk_adj_mom_1m": _entry("Risk-Adj Mom 1M", "ENABLE_RISK_ADJ_MOM_1M", "risk_adj_mom_1m_portfolio_value", "risk_adj_mom_1m_portfolio_history", "risk_adj_mom_1m_cash", "current_risk_adj_mom_1m_stocks"),
    "risk_adj_mom_1m_monthly": _entry("RiskAdj 1M Mth", "ENABLE_RISK_ADJ_MOM_1M_MONTHLY", "risk_adj_mom_1m_monthly_portfolio_value", "risk_adj_mom_1m_monthly_portfolio_history", "risk_adj_mom_1m_monthly_cash", "risk_adj_mom_1m_monthly_positions"),
    "ai_elite": _entry("AI Elite", "ENABLE_AI_ELITE", "ai_elite_portfolio_value", "ai_elite_portfolio_history", "ai_elite_cash", "ai_elite_positions"),
    "ai_elite_monthly_shared": _entry("AI Elite Mth Sh", "ENABLE_AI_ELITE_MONTHLY_SHARED", "ai_elite_monthly_shared_portfolio_value", "ai_elite_monthly_shared_portfolio_history", "ai_elite_monthly_shared_cash", "ai_elite_monthly_shared_positions"),
    "ai_elite_filtered": _entry("AI Elite Flt", "ENABLE_AI_ELITE_FILTERED", "ai_elite_filtered_portfolio_value", "ai_elite_filtered_portfolio_history", "ai_elite_filtered_cash", "ai_elite_filtered_positions"),
    "ai_elite_market_up": _entry("AI Elite Up Sh", "ENABLE_AI_ELITE_MARKET_UP", "ai_elite_market_up_portfolio_value", "ai_elite_market_up_portfolio_history", "ai_elite_market_up_cash", "ai_elite_market_up_positions"),
    "ai_elite_ensemble": _entry("AI Elite Ens", "ENABLE_AI_ELITE_ENSEMBLE", "ai_elite_ensemble_portfolio_value", "ai_elite_ensemble_portfolio_history", "ai_elite_ensemble_cash", "ai_elite_ensemble_positions"),
    "ai_elite_rank_ensemble": _entry("AI Elite Rank", "ENABLE_AI_ELITE_RANK_ENSEMBLE", "ai_elite_rank_ensemble_portfolio_value", "ai_elite_rank_ensemble_portfolio_history", "ai_elite_rank_ensemble_cash", "ai_elite_rank_ensemble_positions"),
    "top5_consistency_blend": _entry("Top5 Cons Blend", "ENABLE_TOP5_CONSISTENCY_BLEND", "top5_consistency_blend_portfolio_value", "top5_consistency_blend_portfolio_history", "top5_consistency_blend_cash", "top5_consistency_blend_positions"),
    "inverse_etf_hedge": _entry("Inv ETF Hedge", "ENABLE_INVERSE_ETF_HEDGE", "inverse_etf_hedge_portfolio_value", "inverse_etf_hedge_portfolio_history", "inverse_etf_hedge_cash", "inverse_etf_hedge_positions"),
    "analyst_rec": _entry("Analyst Rec", "ENABLE_ANALYST_RECOMMENDATION", "analyst_rec_portfolio_value", "analyst_rec_portfolio_history", "analyst_rec_cash", "analyst_rec_positions"),
    "bh_1y_monthly": _entry("BH 1Y Monthly", "ENABLE_STATIC_BH_1Y_MONTHLY", "static_bh_1y_monthly_portfolio_value", "static_bh_1y_monthly_portfolio_history", "static_bh_1y_monthly_cash", "static_bh_1y_monthly_positions"),
    "bh_6m_monthly": _entry("BH 6M Monthly", "ENABLE_STATIC_BH_6M_MONTHLY", "static_bh_6m_monthly_portfolio_value", "static_bh_6m_monthly_portfolio_history", "static_bh_6m_monthly_cash", "static_bh_6m_monthly_positions"),
    "bh_3m_monthly": _entry("BH 3M Monthly", "ENABLE_STATIC_BH_3M_MONTHLY", "static_bh_3m_monthly_portfolio_value", "static_bh_3m_monthly_portfolio_history", "static_bh_3m_monthly_cash", "static_bh_3m_monthly_positions"),
    "bh_1m_monthly": _entry("BH 1M Monthly", "ENABLE_STATIC_BH_1M_MONTHLY", "static_bh_1m_monthly_portfolio_value", "static_bh_1m_monthly_portfolio_history", "static_bh_1m_monthly_cash", "static_bh_1m_monthly_positions"),
    "bb_mean_reversion": _entry("BB Mean Rev", "ENABLE_BB_MEAN_REVERSION", "bb_mean_reversion_value", "bb_mean_reversion_history", "bb_mean_reversion_cash", "bb_mean_reversion_positions"),
    "bb_breakout": _entry("BB Breakout", "ENABLE_BB_BREAKOUT", "bb_breakout_value", "bb_breakout_history", "bb_breakout_cash", "bb_breakout_positions"),
    "bb_squeeze_breakout": _entry("BB Squeeze", "ENABLE_BB_SQUEEZE_BREAKOUT", "bb_squeeze_breakout_value", "bb_squeeze_breakout_history", "bb_squeeze_breakout_cash", "bb_squeeze_breakout_positions"),
    "bb_rsi_combo": _entry("BB RSI Combo", "ENABLE_BB_RSI_COMBO", "bb_rsi_combo_value", "bb_rsi_combo_history", "bb_rsi_combo_cash", "bb_rsi_combo_positions"),
    "trend_breakout": _entry("Trend Breakout", "ENABLE_TREND_BREAKOUT", "trend_breakout_value", "trend_breakout_history", "trend_breakout_cash", "trend_breakout_positions"),
    "static_bh_1y_vol": _entry("BH 1Y Vol Trig", "ENABLE_STATIC_BH_1Y_VOLATILITY", "static_bh_1y_vol_portfolio_value", "static_bh_1y_vol_portfolio_history", "static_bh_1y_vol_cash", "static_bh_1y_vol_positions"),
    "static_bh_1y_perf": _entry("BH 1Y Perf Trig", "ENABLE_STATIC_BH_1Y_PERFORMANCE", "static_bh_1y_perf_portfolio_value", "static_bh_1y_perf_portfolio_history", "static_bh_1y_perf_cash", "static_bh_1y_perf_positions"),
    "static_bh_6m_perf": _entry("BH 6M Perf Trig", "ENABLE_STATIC_BH_6M_PERFORMANCE", "static_bh_6m_perf_portfolio_value", "static_bh_6m_perf_portfolio_history", "static_bh_6m_perf_cash", "static_bh_6m_perf_positions"),
    "static_bh_9m_perf": _entry("BH 9M Perf Trig", "ENABLE_STATIC_BH_9M_PERFORMANCE", "static_bh_9m_perf_portfolio_value", "static_bh_9m_perf_portfolio_history", "static_bh_9m_perf_cash", "static_bh_9m_perf_positions"),
    "bh_1y_1m_rank": _entry("BH 1Y / 1M Rank", "ENABLE_BH_1Y_1M_RANK", "bh_1y_1m_rank_portfolio_value", "bh_1y_1m_rank_portfolio_history", "bh_1y_1m_rank_cash", "current_bh_1y_1m_rank_stocks"),
    "bh_1y_6m_rank": _entry("BH 1Y / 6M Rank", "ENABLE_BH_1Y_6M_RANK", "bh_1y_6m_rank_portfolio_value", "bh_1y_6m_rank_portfolio_history", "bh_1y_6m_rank_cash", "current_bh_1y_6m_rank_stocks"),
    "bh_1y_sma200": _entry("BH 1Y SMA200", "ENABLE_BH_1Y_SMA200", "bh_1y_sma200_portfolio_value", "bh_1y_sma200_portfolio_history", "bh_1y_sma200_cash", "current_bh_1y_sma200_stocks"),
    "bh_1y_fcf_rank": _entry("BH 1Y / FCF Rank", "ENABLE_BH_1Y_FCF_RANK", "bh_1y_fcf_rank_portfolio_value", "bh_1y_fcf_rank_portfolio_history", "bh_1y_fcf_rank_cash", "current_bh_1y_fcf_rank_stocks"),
    "static_bh_1y_mom": _entry("BH 1Y Mom Trig", "ENABLE_STATIC_BH_1Y_MOMENTUM", "static_bh_1y_mom_portfolio_value", "static_bh_1y_mom_portfolio_history", "static_bh_1y_mom_cash", "static_bh_1y_mom_positions"),
    "static_bh_1y_atr": _entry("BH 1Y ATR Trig", "ENABLE_STATIC_BH_1Y_ATR", "static_bh_1y_atr_portfolio_value", "static_bh_1y_atr_portfolio_history", "static_bh_1y_atr_cash", "static_bh_1y_atr_positions"),
    "static_bh_1y_hybrid": _entry("BH 1Y Hybrid Trig", "ENABLE_STATIC_BH_1Y_HYBRID", "static_bh_1y_hybrid_portfolio_value", "static_bh_1y_hybrid_portfolio_history", "static_bh_1y_hybrid_cash", "static_bh_1y_hybrid_positions"),
    "static_bh_1y_volume": _entry("BH 1Y Volume", "ENABLE_STATIC_BH_1Y_VOLUME_FILTER", "static_bh_1y_volume_portfolio_value", "static_bh_1y_volume_portfolio_history", "static_bh_1y_volume_cash", "static_bh_1y_volume_positions"),
    "static_bh_1y_sector": _entry("BH 1Y Sector", "ENABLE_STATIC_BH_1Y_SECTOR_ROTATION", "static_bh_1y_sector_portfolio_value", "static_bh_1y_sector_portfolio_history", "static_bh_1y_sector_cash", "static_bh_1y_sector_positions"),
    "static_bh_1y_perf_threshold": _entry("BH 1Y Perf Thresh", "ENABLE_STATIC_BH_1Y_PERFORMANCE_THRESHOLD", "static_bh_1y_perf_threshold_portfolio_value", "static_bh_1y_perf_threshold_portfolio_history", "static_bh_1y_perf_threshold_cash", "static_bh_1y_perf_threshold_positions"),
    "static_bh_1y_market_regime": _entry("BH 1Y Market Regime", "ENABLE_STATIC_BH_1Y_MARKET_REGIME", "static_bh_1y_market_regime_portfolio_value", "static_bh_1y_market_regime_portfolio_history", "static_bh_1y_market_regime_cash", "static_bh_1y_market_regime_positions"),
    "static_bh_1y_mom_persist": _entry("BH 1Y Mom Persist", "ENABLE_STATIC_BH_1Y_MOMENTUM_PERSIST", "static_bh_1y_mom_persist_portfolio_value", "static_bh_1y_mom_persist_portfolio_history", "static_bh_1y_mom_persist_cash", "static_bh_1y_mom_persist_positions"),
    "static_bh_1y_overlap": _entry("BH 1Y Overlap", "ENABLE_STATIC_BH_1Y_OVERLAP", "static_bh_1y_overlap_portfolio_value", "static_bh_1y_overlap_portfolio_history", "static_bh_1y_overlap_cash", "static_bh_1y_overlap_positions"),
    "static_bh_1y_rank_drift": _entry("BH 1Y Rank Drift", "ENABLE_STATIC_BH_1Y_RANK_DRIFT", "static_bh_1y_rank_drift_portfolio_value", "static_bh_1y_rank_drift_portfolio_history", "static_bh_1y_rank_drift_cash", "static_bh_1y_rank_drift_positions"),
    "static_bh_1y_drawdown": _entry("BH 1Y Drawdown", "ENABLE_STATIC_BH_1Y_DRAWDOWN", "static_bh_1y_drawdown_portfolio_value", "static_bh_1y_drawdown_portfolio_history", "static_bh_1y_drawdown_cash", "static_bh_1y_drawdown_positions"),
    "static_bh_1y_smart_monthly": _entry("BH 1Y Smart Mth", "ENABLE_STATIC_BH_1Y_SMART_MONTHLY", "static_bh_1y_smart_monthly_portfolio_value", "static_bh_1y_smart_monthly_portfolio_history", "static_bh_1y_smart_monthly_cash", "static_bh_1y_smart_monthly_positions"),
    "bh_1y_mom_sell": _entry("BH 1Y Mom Sell", "ENABLE_BH_1Y_MOM_SELL", "bh_1y_mom_sell_portfolio_value", "bh_1y_mom_sell_portfolio_history", "bh_1y_mom_sell_cash", "bh_1y_mom_sell_positions"),
    "bh_1y_rank_sell": _entry("BH 1Y Rank Sell", "ENABLE_BH_1Y_RANK_SELL", "bh_1y_rank_sell_portfolio_value", "bh_1y_rank_sell_portfolio_history", "bh_1y_rank_sell_cash", "bh_1y_rank_sell_positions"),
    "bh_1y_trailing_mom": _entry("BH 1Y Trail Mom", "ENABLE_BH_1Y_TRAILING_MOM", "bh_1y_trailing_mom_portfolio_value", "bh_1y_trailing_mom_portfolio_history", "bh_1y_trailing_mom_cash", "bh_1y_trailing_mom_positions"),
    "bh_1y_volume_confirm": _entry("BH 1Y Vol Conf", "ENABLE_BH_1Y_VOLUME_CONFIRM", "bh_1y_volume_confirm_portfolio_value", "bh_1y_volume_confirm_portfolio_history", "bh_1y_volume_confirm_cash", "bh_1y_volume_confirm_positions"),
    "bh_1y_sector_aware": _entry("BH 1Y Sect Aware", "ENABLE_BH_1Y_SECTOR_AWARE", "bh_1y_sector_aware_portfolio_value", "bh_1y_sector_aware_portfolio_history", "bh_1y_sector_aware_cash", "bh_1y_sector_aware_positions"),
    "bh_1y_accel_buy": _entry("BH 1Y Accel", "ENABLE_BH_1Y_ACCEL_BUY", "bh_1y_accel_buy_portfolio_value", "bh_1y_accel_buy_portfolio_history", "bh_1y_accel_buy_cash", "bh_1y_accel_buy_positions"),
    "static_bh_3m_accel": _entry("Static BH 3M Accel", "ENABLE_STATIC_BH_3M_ACCEL", "static_bh_3m_accel_portfolio_value", "static_bh_3m_accel_portfolio_history", "static_bh_3m_accel_cash", "static_bh_3m_accel_positions"),
    "bh_1y_vol_adj_rebal": _entry("Rebal 1Y VolAdj", "ENABLE_BH_1Y_VOL_ADJ_REBAL", "bh_1y_vol_adj_rebal_portfolio_value", "bh_1y_vol_adj_rebal_portfolio_history", "bh_1y_vol_adj_rebal_cash", "bh_1y_vol_adj_rebal_positions"),
    "ratio_1m3m_vol_adj_rebal": _entry("Rebal 1M3M VolAdj", "ENABLE_RATIO_1M3M_VOL_ADJ_REBAL", "ratio_1m3m_vol_adj_rebal_portfolio_value", "ratio_1m3m_vol_adj_rebal_portfolio_history", "ratio_1m3m_vol_adj_rebal_cash", "ratio_1m3m_vol_adj_rebal_positions"),
    "bh_1y_corr_filter": _entry("Rebal 1Y CorrFilt", "ENABLE_BH_1Y_CORR_FILTER", "bh_1y_corr_filter_portfolio_value", "bh_1y_corr_filter_portfolio_history", "bh_1y_corr_filter_cash", "bh_1y_corr_filter_positions"),
    "bh_1y_regime_aware": _entry("Rebal 1Y Regime", "ENABLE_BH_1Y_REGIME_AWARE", "bh_1y_regime_aware_portfolio_value", "bh_1y_regime_aware_portfolio_history", "bh_1y_regime_aware_cash", "bh_1y_regime_aware_positions"),
    "bh_1y_risk_parity": _entry("Rebal 1Y RiskPar", "ENABLE_BH_1Y_RISK_PARITY", "bh_1y_risk_parity_portfolio_value", "bh_1y_risk_parity_portfolio_history", "bh_1y_risk_parity_cash", "bh_1y_risk_parity_positions"),
    "bh_1y_drift_thresh": _entry("Rebal 1Y Drift", "ENABLE_BH_1Y_DRIFT_THRESH", "bh_1y_drift_thresh_portfolio_value", "bh_1y_drift_thresh_portfolio_history", "bh_1y_drift_thresh_cash", "bh_1y_drift_thresh_positions"),
    "bh_1y_mom_quality": _entry("Rebal 1Y MomQual", "ENABLE_BH_1Y_MOM_QUALITY", "bh_1y_mom_quality_portfolio_value", "bh_1y_mom_quality_portfolio_history", "bh_1y_mom_quality_cash", "bh_1y_mom_quality_positions"),
    "bh_1y_liquidity": _entry("Rebal 1Y Liquid", "ENABLE_BH_1Y_LIQUIDITY", "bh_1y_liquidity_portfolio_value", "bh_1y_liquidity_portfolio_history", "bh_1y_liquidity_cash", "bh_1y_liquidity_positions"),
    "bh_1y_earnings_avoid": _entry("Rebal 1Y EarnAvd", "ENABLE_BH_1Y_EARNINGS_AVOID", "bh_1y_earnings_avoid_portfolio_value", "bh_1y_earnings_avoid_portfolio_history", "bh_1y_earnings_avoid_cash", "bh_1y_earnings_avoid_positions"),
    "bh_1y_multi_factor": _entry("Rebal 1Y MultiFact", "ENABLE_BH_1Y_MULTI_FACTOR", "bh_1y_multi_factor_portfolio_value", "bh_1y_multi_factor_portfolio_history", "bh_1y_multi_factor_cash", "bh_1y_multi_factor_positions"),
    "bh_1y_time_decay": _entry("Rebal 1Y TimeDec", "ENABLE_BH_1Y_TIME_DECAY", "bh_1y_time_decay_portfolio_value", "bh_1y_time_decay_portfolio_history", "bh_1y_time_decay_cash", "bh_1y_time_decay_positions"),
}


def get_canonical_strategy_names() -> List[str]:
    return sorted(STRATEGY_REGISTRY.keys())
